FROM node:alpine as build

# set working directory
WORKDIR /app
# copy everything to /app directory
COPY . /app
# add the node_modules folder to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache dependencies
RUN npm install 

#build the project for production
RUN npm run build

# set up production environment
FROM nginx:alpine

# copy the build folder from react to the root of nginx (www)
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 3000

# remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf
# replace with custom one
COPY --from=build /app/config/nginx/nginx.conf /etc/nginx/conf.d


CMD ["nginx", "-g", "daemon off;"]